# Generated by Django 5.2.10 on 2026-01-31 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, unique=True, verbose_name="адрес"),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="широта"),
                ),
                (
                    "lon",
                    models.FloatField(blank=True, null=True, verbose_name="долгота"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="дата обновления",
                    ),
                ),
            ],
            options={
                "verbose_name": "место",
                "verbose_name_plural": "места",
            },
        ),
    ]
