# Generated by Django 5.2.10 on 2026-01-31 17:11

from django.db import migrations


def fill_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.iterator():
        item.price = item.product.price
        item.save(update_fields=['price'])


def rollback_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    OrderItem.objects.update(price=None)


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_add_price_to_orderitem"),
    ]

    operations = [
        migrations.RunPython(fill_prices, rollback_prices),
    ]
