# Generated by Django 5.2.10 on 2026-01-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0040_fill_orderitem_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unprocessed", "Необработанный"),
                    ("cooking", "Готовится"),
                    ("delivering", "В доставке"),
                    ("completed", "Выполнен"),
                ],
                db_index=True,
                default="unprocessed",
                max_length=20,
                verbose_name="статус",
            ),
        ),
    ]
