# Generated by Django 5.2.10 on 2026-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0041_add_status_to_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, verbose_name="комментарий"),
        ),
    ]
