# Generated by Django 5.2.10 on 2026-01-31 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0042_add_comment_to_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="дата звонка"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="дата доставки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="registered_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="зарегистрирован",
            ),
        ),
    ]
