# Generated by Django 5.2.10 on 2026-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_add_datetime_fields_to_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличностью"), ("online", "Электронно")],
                db_index=True,
                default="",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
    ]
