# Generated by Django 5.2.10 on 2026-02-04 15:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0045_add_restaurant_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, verbose_name="телефон"
            ),
        ),
    ]
